bind_service_name: bind9
bind_conf_dir: /etc/bind
bind_conf_file: "{{ bind_conf_dir }}/named.conf"
bind_data_dir: /var/lib/bind
bind_cache_dir: /var/cache/bind
bind_user: root
bind_group: bind
bind_packages:
  - bind9
  - bind9-utils
bind_namedca_file: "/usr/share/dns/root.hints"
bind_default_zones: |
  zone "." { type hint; file "{{ bind_namedca_file }}"; };
# zone "localhost" { type master; file "/etc/bind/db.local"; };
# zone "127.in-addr.arpa" { type master; file "/etc/bind/db.127"; };
# zone "0.in-addr.arpa"  { type master; file "/etc/bind/db.0"; };
# zone "255.in-addr.arpa" { type master; file "/etc/bind/db.255"; };
