- name: Distribution specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Distribution specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml"

- name: create dirs
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root')}}"
    mode: "{{ item.mode | default('0755')}}"
  loop: 
    - path: "{{ openssl_key_dir }}"
    - path: "{{ openssl_cert_dir }}"

- name: Create key {{ openssl_createsscert_key_path }}
  community.crypto.openssl_privatekey:
    force: false
    owner: root
    group: root
    mode: '0600'
    path: "{{ openssl_createsscert_key_path }}"
    size: "{{ openssl_createsscert_key_size }}"
    type: "{{ openssl_createsscert_key_type }}"

- name: Create csr
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ openssl_createsscert_key_path }}"
    common_name: "{{ ansible_nodename }}"
    organization_name: "{{ openssl_createsscert_organization_name }}"
    subject_alt_name: "{{ openssl_createsscert_san }}"
  register: openssl_createsscert_csr_result
  changed_when: false
  
- name: Create crt {{ openssl_createsscert_crt_path | basename }}
  community.crypto.x509_certificate:
    path: "{{ openssl_createsscert_crt_path }}"
    csr_content: "{{ openssl_createsscert_csr_result.csr }}"
    privatekey_path: "{{ openssl_createsscert_key_path }}"
    provider: selfsigned
  when: openssl_create_csronly is false

- name: Fetch crt {{ openssl_createsscert_crt_path | basename }}
  ansible.builtin.fetch:
    src: "{{ openssl_createsscert_crt_path }}"
    flat: true
    dest: files/
  when: openssl_create_csronly is false

- name: Fetch {{ ansible_nodename }}.csr 
  local_action: 
    module: ansible.builtin.copy 
    content: "{{ openssl_createsscert_csr_result.csr }}"
    dest: "files/{{ ansible_nodename }}.csr"
  when: openssl_create_csronly is true
