haproxy_packages:
  - epel-release
  - haproxy

haproxy_global:
  log: 
    - 127.0.0.1 local2
  chroot: /var/lib/haproxy
  pidfile: /var/run/haproxy.pid
  maxconn: 4000
  user: haproxy
  group: haproxy
  other_options:
    - daemon
    - stats socket /var/lib/haproxy/stats
    - ssl-default-bind-ciphers PROFILE=SYSTEM
    - ssl-default-server-ciphers PROFILE=SYSTEM

haproxy_defaults:
  mode: http
  log: global
  maxconn: 3000
  retries: 3
  options:
    - httplog
    - dontlognull
    - http-server-close
    - forwardfor except 127.0.0.0/8
    - redispatch
  timeouts:
    - http-request 10s
    - queue 1m
    - connect 10s
    - client 1m
    - server 1m
    - http-keep-alive 10s
    - check 10s
