haproxy_packages:
  - haproxy

haproxy_global:
  log: 
    - "/dev/log local0"
    - "/dev/log local1 notice"
  chroot: /var/lib/haproxy
  pidfile: /var/run/haproxy.pid
  maxconn: 4000
  user: haproxy
  group: haproxy
  other_options:
    - daemon
    - stats socket /run/haproxy/admin.sock mode 660 level admin
    - stats timeout 30s
    - ca-base /etc/ssl/certs
    - crt-base /etc/ssl/private
    - ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    - ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    - ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

haproxy_defaults:
  mode: http
  log: global
  maxconn: 3000
  retries: 3
  options:
    - httplog
    - dontlognull
  timeouts:
    - http-request 10s
    - queue 1m
    - connect 5000
    - client 50000
    - server 50000
  errorfiles:
    - "400 /etc/haproxy/errors/400.http"
    - "403 /etc/haproxy/errors/403.http"
    - "408 /etc/haproxy/errors/408.http"
    - "500 /etc/haproxy/errors/500.http"
    - "502 /etc/haproxy/errors/502.http"
    - "503 /etc/haproxy/errors/503.http"
    - "504 /etc/haproxy/errors/504.http"
  
haproxy_systemd_dropin:
  - dir: /etc/systemd/system/haproxy.service.d
    file: override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -f {{ haproxy_confd_dir }} -p $PIDFILE $EXTRAOPTS
      ExecReload=
      ExecReload=/usr/sbin/haproxy -Ws -f $CONFIG -f {{ haproxy_confd_dir }} -c -q $EXTRAOPTS
      ExecReload=/bin/kill -USR2 $MAINPID
